version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "51213:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
      NEXTAUTH_SECRET: "YOUR_NEXTAUTH_SECRET_HERE" # Replace with a strong secret in production
      NEXT_PUBLIC_SOCKET_URL: "http://localhost:3001" # Or the public URL of your socket server
    depends_on:
      - db
      - socket-server

  socket-server:
    build:
      context: .
      dockerfile: socket-server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      CORS_ORIGIN: "http://localhost:3000" # Set your Next.js frontend URL here for production
    volumes:
      - ./socket-server:/app
      - /app/node_modules # Exclude node_modules from host bind mount

volumes:
  db_data: