version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "51213:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: